### ISSUE TITLE
Unable to NewRelic instrumentation for redis

### ISSUE THREAD

**Issue by satish-gathole** [evanphx/newrelic-redis#14]
As per instructions I added this gem to my Gemfile and run bundle install. No it should start tracking redis but unble to see any log on new-relic.

Could someone please help me ? and let me know what is the correct way to make it work.

Also please let me know where I can see redis logs on NewRelic dashboard.

**Comment by shaneog** [comment]
Same problem for me... Where am I supposed to see the Redis times?

**Comment by evanphx** [comment]
@jasonrclark can probably chime in here and tell you where to find the data.

**Comment by jasonrclark** [comment]
Glad to chime in. First off, would highly recommend moving up to `newrelic_rpm` 3.11.1 + `newrelic-redis` 2.0.2 for the best results. There have been some recent changes that are worth the upgrade to get in on.

From there, you should see the data showing up in a few different places:
* Databases tab
* Specific transaction pages
* If a transaction trace is captured and appropriate settings are on, keys will be shown in the tree alongside the call (there's a magnifying glass icon next to the call if we captured keys)

Here's what a few of those spots look like for reference:

**Databases**
![image](https://cloud.githubusercontent.com/assets/130504/6717569/a6109694-cd6a-11e4-96e9-e2b4534a0a2e.png)

**Transaction trace**
![image](https://cloud.githubusercontent.com/assets/130504/6717581/bdc96748-cd6a-11e4-876f-578c71095480.png)

Hope that helps!

**Comment by shaneog** [comment]
Thanks @jasonrclark  - I'll give it another go.

@evanphx I think it's worth adding this info + screenshots to the README

**Comment by evanphx** [comment]
@jasonrclark is there a help page on newrelic.com that I can add a link to in the Readme?

**Comment by jasonrclark** [comment]
@evanphx We've been linking to https://docs.newrelic.com/docs/apm/applications-menu/monitoring/databases-slow-queries-dashboard as our primary documentation. Thanks!

**Comment by mickey** [comment]
Just wanted to confirm it works with the latest versions.
It also appears on the service maps :+1: :heart:
