### ISSUE TITLE
Change the metric name from Database/Redis/allWeb to Datastore/Redis/allWeb

### ISSUE THREAD

**Issue by D1plo1d** [evanphx/newrelic-redis#17]
Quoting https://docs.newrelic.com/docs/apm/apis/application-examples-v2/obtaining-web-transaction-response-time-data-v2#datastore-v-database

> As of February 2015, the New Relic agents (starting with Python) will begin to display the database time broken out into specific database types. Agents will replace the Database metric name with Datastore/${DBTYPE}, where ${DBTYPE} will identify the appropriate database; for example, Postgres, MongoDB, MSSQL, ODBC, Redis, SQLite, Memcached, etc.

Would it be possible to make use of `Datastore/${DBTYPE}` in the newrelic-redis gem? It sounds like it's an all around improvement over `Database/${DBTYPE}`.

**Comment by evanphx** [comment]
Sure! Want to send over a PR to do the change?

**Comment by D1plo1d** [comment]
Done!
